### ISSUE TITLE
[BUG] File not found error

### ISSUE THREAD

**Issue by Hunam6** [tsunematsu21/actions-publish-gh-pages#6]
**Describe the bug**
Running into an error when using the action.

**To Reproduce**
My workflow:
```
name: Publish to GitHub Pages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
        with:
          dir: src
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
```

**Expected behavior**
Publish my site to the `gh-pages` branch

**Screenshot**
![](https://user-images.githubusercontent.com/38606542/79241182-00530100-7e73-11ea-9f00-27a95e9ec6a6.png)
